# build-windows.ps1 — Builds a static FFmpeg via vcpkg for thumbrella.
# Run from the project root:  powershell -File ffs\build-windows.ps1
#
# This clones vcpkg into ffs/vcpkg/, bootstraps it, and installs a minimal
# static FFmpeg with only the decoders/demuxers/parsers thumbrella needs.
# On success, writes VCPKG_ROOT to .cargo/ffs.toml so cargo picks it up.

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
Set-Location $ProjectRoot

$vcpkgDir = Join-Path $ScriptDir "vcpkg"

# ---- Clone vcpkg if not already present ----
if (-not (Test-Path $vcpkgDir)) {
    Write-Host "==> Cloning vcpkg into $vcpkgDir ..."
    # Pinned to vcpkg release with Ffmpeg 8.1.2
    git clone --depth 1 --branch 2026.06.24 https://github.com/Microsoft/vcpkg.git $vcpkgDir
}

# ---- Bootstrap vcpkg ----
Write-Host "==> Bootstrapping vcpkg ..."
Push-Location $vcpkgDir
try {
    .\bootstrap-vcpkg.bat
} finally {
    Pop-Location
}

# ---- Apply our patches to the vcpkg port ----
Write-Host "==> Applying port patches ..."
Push-Location $vcpkgDir
try {
    foreach ($patch in Get-ChildItem (Join-Path $ScriptDir "ports/ffmpeg/*.patch")) {
        Write-Host "  Applying $($patch.Name)"
        git apply $patch.FullName
    }
} finally {
    Pop-Location
}

# ---- Install ffmpeg (static, overlay port: selective build, no hw accel) ----
Write-Host "==> Installing ffmpeg via vcpkg (~10-15 min, builds from source) ..."
$vcpkgExe = Join-Path $vcpkgDir "vcpkg.exe"
& $vcpkgExe install ffmpeg[avcodec,avdevice,avfilter,avformat,swresample,swscale,zlib,bzip2,lzma] `
    --overlay-triplets="$ScriptDir/triplets" `
    --triplet=x64-windows-static

Write-Host ""
Write-Host "============================================"
Write-Host "FFmpeg built successfully!"
Write-Host "Location: $vcpkgDir"
Write-Host ""

# Write .cargo/ffs.toml so cargo finds vcpkg FFmpeg without env vars.
$cargoDir = Join-Path $ProjectRoot ".cargo"
if (-not (Test-Path $cargoDir)) { New-Item -ItemType Directory -Path $cargoDir | Out-Null }
$ffsToml = Join-Path $cargoDir "ffs.toml"
$absVcpkg = (Resolve-Path $vcpkgDir).Path -replace '\\', '/'
@"
# Generated by ffs/build-windows.ps1 — do not edit
[env]
VCPKG_ROOT = { value = "$absVcpkg", force = true }
"@ | Set-Content -Path $ffsToml

Write-Host "Wrote .cargo/ffs.toml (VCPKG_ROOT=$absVcpkg)"
Write-Host "Now run:  cargo build --release -p tier3"
Write-Host "============================================"
