# build-windows.ps1, Builds a static FFmpeg via vcpkg for thumbrella.
# Run from the project root:  powershell -File ffs\build-windows.ps1
#
# This clones vcpkg into ffs/vcpkg/, bootstraps it, and installs a minimal
# static FFmpeg with only the decoders/demuxers/parsers thumbrella needs.
# On success, writes VCPKG_ROOT to .cargo/ffs.toml so cargo picks it up.

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
Set-Location $ProjectRoot

$vcpkgDir = Join-Path $ScriptDir "vcpkg"
$vcpkgCommit = "e456309491fd875487bf02b8a0dca76c1b1b00cc" # FFmpeg 9.0.2, port revision 1

# ---- Clone vcpkg if not already present ----
if (-not (Test-Path $vcpkgDir)) {
    Write-Host "==> Cloning vcpkg into $vcpkgDir ..."
    git init $vcpkgDir
    if ($LASTEXITCODE -ne 0) { throw "Could not initialize vcpkg" }
    git -C $vcpkgDir remote add origin https://github.com/Microsoft/vcpkg.git
    if ($LASTEXITCODE -ne 0) { throw "Could not configure vcpkg remote" }
    git -C $vcpkgDir fetch --depth 1 origin $vcpkgCommit
    if ($LASTEXITCODE -ne 0) { throw "Could not fetch pinned vcpkg commit" }
    git -C $vcpkgDir checkout --detach $vcpkgCommit
    if ($LASTEXITCODE -ne 0) { throw "Could not check out pinned vcpkg commit" }
}

$head = git -C $vcpkgDir rev-parse HEAD
if ($LASTEXITCODE -ne 0 -or $head -ne $vcpkgCommit) {
    throw "Existing ffs/vcpkg is not the FFmpeg 9.0.2 baseline. Move it aside or remove it, then rerun this script."
}
$port = Get-Content (Join-Path $vcpkgDir "ports/ffmpeg/vcpkg.json") -Raw | ConvertFrom-Json
if ($port.version -ne "9.0.2") { throw "Pinned vcpkg port must provide FFmpeg 9.0.2" }

# ---- Bootstrap vcpkg ----
Write-Host "==> Bootstrapping vcpkg ..."
Push-Location $vcpkgDir
try {
    .\bootstrap-vcpkg.bat
    if ($LASTEXITCODE -ne 0) { throw "vcpkg bootstrap failed" }
} finally {
    Pop-Location
}

# ---- Apply our patches to the vcpkg port ----
Write-Host "==> Applying port patches ..."
Push-Location $vcpkgDir
try {
    foreach ($patch in Get-ChildItem (Join-Path $ScriptDir "ports/ffmpeg/*.patch")) {
        Write-Host "  Applying $($patch.Name)"
        git apply --check $patch.FullName
        if ($LASTEXITCODE -eq 0) {
            git apply $patch.FullName
            if ($LASTEXITCODE -ne 0) { throw "Could not apply $($patch.Name)" }
        } else {
            git apply --reverse --check $patch.FullName
            if ($LASTEXITCODE -ne 0) { throw "Port patch $($patch.Name) does not match the pinned vcpkg tree" }
            Write-Host "  Already applied"
        }
    }
} finally {
    Pop-Location
}

# ---- Install ffmpeg (static, overlay port: selective build, no hw accel) ----
Write-Host "==> Installing ffmpeg via vcpkg (~10-15 min, builds from source) ..."
$vcpkgExe = Join-Path $vcpkgDir "vcpkg.exe"
& $vcpkgExe install ffmpeg[avcodec,avdevice,avfilter,avformat,swresample,swscale,zlib,bzip2,lzma] `
    --overlay-triplets="$ScriptDir/triplets" `
    --triplet=x64-windows-static
if ($LASTEXITCODE -ne 0) { throw "vcpkg FFmpeg install failed" }

Write-Host ""
Write-Host "============================================"
Write-Host "FFmpeg built successfully!"
Write-Host "Location: $vcpkgDir"
Write-Host ""

# Write .cargo/ffs.toml so cargo finds vcpkg FFmpeg without env vars.
$cargoDir = Join-Path $ProjectRoot ".cargo"
if (-not (Test-Path $cargoDir)) { New-Item -ItemType Directory -Path $cargoDir | Out-Null }
$ffsToml = Join-Path $cargoDir "ffs.toml"
$absVcpkg = (Resolve-Path $vcpkgDir).Path -replace '\\', '/'
@"
# Generated by ffs/build-windows.ps1, do not edit
[env]
VCPKG_ROOT = { value = "$absVcpkg", force = true }
"@ | Set-Content -Path $ffsToml

Write-Host "Wrote .cargo/ffs.toml (VCPKG_ROOT=$absVcpkg)"
Write-Host "Now run:  cargo build --release -p tier3"
Write-Host "============================================"
